import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function generateReport(resume) {
  const doc = new jsPDF();

  const cleanText = (text = "") =>
    String(text)
      .replace(/[\u0000-\u001F\u007F-\u009F]/g, "")
      .replace(/\u00AD/g, "")
      .replace(/\u2011/g, "-")
      .replace(/\s+/g, " ")
      .trim();

  const ai = resume?.aiFeedback || {};
  const analysis = resume?.analysis || {};
  const jobMatch = resume?.jobMatch || {};

  // Header
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 40, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(255);
  doc.text("HireSense AI", 105, 16, {
    align: "center",
  });

  doc.setFontSize(13);
  doc.text("AI Resume Analysis Report", 105, 26, {
    align: "center",
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 105, 34, {
    align: "center",
  });

  // Candidate
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text("Candidate Information", 20, 48);

  autoTable(doc, {
    startY: 55,
    theme: "grid",
    head: [["Field", "Value"]],
    body: [
      ["Name", analysis.personalInfo?.name || "-"],
      ["Email", analysis.personalInfo?.email || "-"],
      ["Phone", analysis.personalInfo?.phone || "-"],
      ["Location", analysis.personalInfo?.location || "-"],
    ],
  });

  // Scores
  doc.setFontSize(16);
  doc.text("Overall Scores", 20, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    styles: {
      font: "helvetica",
      fontSize: 10,
      cellPadding: 3,
      overflow: "linebreak",
      valign: "middle",
      tableWidth: "wrap",
      halign: "left",
    },
    startY: doc.lastAutoTable.finalY + 20,
    head: [["Metric", "Value"]],
    body: [
      ["Resume Rating", `${ai.overallRating || "-"}/10`],

      ["Hiring Probability", `${ai.hiringProbability || 0}%`],

      [
        "Job Match",
        `${
          jobMatch.matchPercentage ??
          jobMatch.score ??
          jobMatch.matchScore ??
          "-"
        }%`,
      ],
    ],
  });

  // Technical Skills
  doc.setFontSize(16);
  doc.text("Technical Skills", 20, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    styles: {
      font: "helvetica",
      fontSize: 10,
      cellPadding: 3,
      overflow: "linebreak",
      valign: "middle",
      tableWidth: "wrap",
      halign: "left",
    },

    startY: doc.lastAutoTable.finalY + 20,
    body: (analysis.skills?.technical || []).map((skill) => [skill]),
  });

  // Strengths
  doc.setFontSize(16);
  doc.text("Strengths", 20, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    styles: {
      font: "helvetica",
      fontSize: 10,
      cellPadding: 3,
      overflow: "linebreak",
      valign: "middle",
      tableWidth: "wrap",
      halign: "left",
    },
    startY: doc.lastAutoTable.finalY + 20,
    body: (ai.strengths || []).map((item) => [item]),
  });

  // Weaknesses
  doc.setFontSize(16);
  doc.text("Weaknesses", 20, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    styles: {
      font: "helvetica",
      fontSize: 10,
      cellPadding: 3,
      overflow: "linebreak",
      valign: "middle",
      tableWidth: "wrap",
      halign: "left",
    },
    startY: doc.lastAutoTable.finalY + 20,
    body: (ai.weaknesses || []).map((item) => [item]),
  });

  // Missing Skills
  doc.setFontSize(16);
  doc.text("Missing Skills", 20, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    styles: {
      font: "helvetica",
      fontSize: 10,
      cellPadding: 3,
      overflow: "linebreak",
      valign: "middle",
      tableWidth: "wrap",
      halign: "left",
    },
    startY: doc.lastAutoTable.finalY + 20,
    body: (ai.missingSkills?.length
      ? ai.missingSkills
      : jobMatch.missingSkills || []
    ).map((item) => [cleanText(item)]),
  });

  // Recommendations
  doc.setFontSize(16);
  doc.text("AI Recommendations", 20, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    styles: {
      font: "helvetica",
      fontSize: 10,
      cellPadding: 3,
      overflow: "linebreak",
      valign: "middle",
      tableWidth: "wrap",
      halign: "left",
    },
    startY: doc.lastAutoTable.finalY + 20,
    body: (ai.improvements || jobMatch.recommendations || []).map((item) => [
      item,
    ]),
  });

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text("Generated by HireSense Ai ", 105, 285, {
    align: "center",
  });

  doc.save("Resume-Analysis-Report.pdf");
}
