import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function generateReport(resume) {
  const doc = new jsPDF();

  const ai = resume?.aiFeedback || {};
  const analysis = resume?.analysis || {};
  const jobMatch = resume?.jobMatch || {};

  // Header
  doc.setFontSize(22);
  doc.setTextColor(37, 99, 235);
  doc.text("Azure Resume Analyzer AI", 105, 20, {
    align: "center",
  });

  doc.setFontSize(14);
  doc.setTextColor(100);
  doc.text("Professional Resume Analysis Report", 105, 30, {
    align: "center",
  });

  doc.setDrawColor(37, 99, 235);
  doc.line(20, 35, 190, 35);

  // Candidate
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text("Candidate Information", 20, 48);

  autoTable(doc, {
    startY: 55,
    theme: "grid",
    head: [["Field", "Value"]],
    body: [
      ["Name", analysis.personalInfo?.name || "-"],
      ["Email", analysis.personalInfo?.email || "-"],
      ["Phone", analysis.personalInfo?.phone || "-"],
      ["Location", analysis.personalInfo?.location || "-"],
    ],
  });

  // Scores
  doc.setFontSize(16);
  doc.text("Overall Scores", 20, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    head: [["Metric", "Value"]],
    body: [
      ["Resume Rating", `${ai.overallRating || "-"} / 10`],
      ["Hiring Probability", `${ai.hiringProbability || 0}%`],
      ["Job Match", `${jobMatch.matchPercentage || 0}%`],
    ],
  });

  // Technical Skills
  doc.setFontSize(16);
  doc.text("Technical Skills", 20, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    body: (analysis.skills?.technical || []).map((skill) => [skill]),
  });

  // Strengths
  doc.setFontSize(16);
  doc.text("Strengths", 20, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    body: (ai.strengths || []).map((item) => [item]),
  });

  // Weaknesses
  doc.setFontSize(16);
  doc.text("Weaknesses", 20, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    body: (ai.weaknesses || []).map((item) => [item]),
  });

  // Missing Skills
  doc.setFontSize(16);
  doc.text("Missing Skills", 20, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    body: (jobMatch.missingSkills || []).map((item) => [item]),
  });

  // Recommendations
  doc.setFontSize(16);
  doc.text("AI Recommendations", 20, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    body: (ai.improvements || jobMatch.recommendations || []).map((item) => [
      item,
    ]),
  });

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(
    "Generated by Azure Resume Analyzer AI",
    105,
    285,
    {
      align: "center",
    }
  );

  doc.save("Resume-Analysis-Report.pdf");
}