import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function generateReport(resume) {
  const doc = new jsPDF();

  const ai = resume?.aiFeedback || {};
  const analysis = resume?.analysis || {};
  const jobMatch = resume?.jobMatch || {};

  // Header
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 40, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(255);
  doc.text("HireSense AI", 105, 16, {
    align: "center",
  });

  doc.setFontSize(13);
  doc.text("AI Resume Analysis Report", 105, 26, {
    align: "center",
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 105, 34, {
    align: "center",
  });

  // Candidate
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text("Candidate Information", 20, 48);

  autoTable(doc, {
    startY: 55,
    theme: "grid",
    headStyles: {
      fillColor: [31, 41, 55],
    },
    head: [["Field", "Value"]],
    body: [
      ["Name", analysis.personalInfo?.name || "-"],
      ["Email", analysis.personalInfo?.email || "-"],
      ["Phone", analysis.personalInfo?.phone || "-"],
      ["Location", analysis.personalInfo?.location || "-"],
    ],
  });

  // Scores
  doc.setFontSize(16);
  doc.text("Overall Scores", 20, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    head: [["Metric", "Value"]],
    body: [
      ["⭐ Resume Rating", `${ai.overallRating || "-"}/10`],

      ["📈 Hiring Probability", `${ai.hiringProbability || 0}%`],

      ["🎯 Job Match", `${jobMatch.matchPercentage || 0}%`],
    ],
  });

  // Technical Skills
  doc.setFontSize(16);
  doc.text("Technical Skills", 20, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    body: [[(analysis.skills?.technical || []).join("   •   ")]],
  });

  // Strengths
  doc.setFontSize(16);
  doc.text("Strengths", 20, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    body: (ai.strengths || []).map((item) => [item]),
  });

  // Weaknesses
  doc.setFontSize(16);
  doc.text("Weaknesses", 20, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    body: (ai.weaknesses || []).map((item) => [item]),
  });

  // Missing Skills
  doc.setFontSize(16);
  doc.text("Missing Skills", 20, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    body: (jobMatch.missingSkills || []).map((item) => [item]),
  });

  // Recommendations
  doc.setFontSize(16);
  doc.text("AI Recommendations", 20, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    body: (ai.improvements || jobMatch.recommendations || []).map((item) => [
      item,
    ]),
  });

  doc.setFontSize(16);
  doc.setTextColor(37, 99, 235);

  doc.text("Executive Summary", 20, doc.lastAutoTable.finalY + 15);

  const summary = `This resume received an overall rating of ${
    ai.overallRating || "-"
  }/10 with an estimated hiring probability of ${
    ai.hiringProbability || 0
  }%. The profile demonstrates ${
    ai.strengths?.[0]?.toLowerCase() || "good technical skills"
  }. Focus on ${
    ai.weaknesses?.[0]?.toLowerCase() || "continuous improvement"
  } to improve interview chances.`;

  doc.setFontSize(11);

  doc.setTextColor(70);

  doc.text(summary, 20, doc.lastAutoTable.finalY + 23, {
    maxWidth: 170,
  });

  // Footer
  doc.setDrawColor(220);

  doc.line(20, 280, 190, 280);

  doc.setFontSize(9);

  doc.setTextColor(120);

  doc.text(
    "Generated by HireSense AI | AI Powered Resume Intelligence",
    105,
    286,
    {
      align: "center",
    },
  );

  doc.save("Resume-Analysis-Report.pdf");
}
